name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main", "lab2/d" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Завантажуємо код проєкту
        uses: actions/checkout@v4

      - name: Авторизація в GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Збираємо (Build) та відправляємо (Push) образ
        run: |
          docker build -t ghcr.io/edyky2006/pythonmath:latest .
          docker push ghcr.io/edyky2006/pythonmath:latest


  test-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Авторизація в GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Стягуємо (Pull) контейнер та запускаємо тести
        run: |
          docker pull ghcr.io/edyky2006/pythonmath:latest
          docker run ghcr.io/edyky2006/pythonmath:latest pytest